[package]
name = "consulta_fecha_de_racionamiento_agua_bogot√°_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0.117"
tokio = { version = "1", features = ["full"] }
